version: 2 

seeds: 
  - name: product
    config: 
      schema: production
      column_types: 
        productid: integer
        name: varchar(255)
        safetystocklevel: smallint
        finishedgoodsflag: boolean 
        class: varchar(255)
        makeflag: boolean
        productnumber: varchar(255)
        reorderpoint: smallint
        modifieddate: timestamp
        rowguid: varchar(255)
        productmodelid: integer
        weightunitmeasurecode: varchar(255)
        standardcost: numeric
        productsubcategoryid: integer
        listprice: numeric
        daystomanufacture: integer
        productline: varchar(255)
        color: varchar(255)
        sellstartdate: timestamp
        weight: numeric
